version: '3.8'

services:
  staff-db:
    image: postgres:14
    container_name: staff-db
    restart: always
    ports:
      - "5605:5432"
    environment:
      POSTGRES_DB: staff
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata_staff:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
    container_name: staff-backend
    ports:
      - "3605:3605"
    env_file:
      - ./Backend/.env
    depends_on:
      - staff-db

  staff-ui:
    build:
      context: ./Staff
    container_name: staff-ui
    ports:
      - "8610:80"
    depends_on:
      - backend

volumes:
  pgdata_staff:

